import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header username="Marcus" />
        {children}
      </body>
      <Script src="https://t.contentsquare.net/uxa/dd1a8ff2ab2fd.js" defer strategy="afterInteractive" />
    </html>
  );
}
